

```
# Documentacion
https://estadisticasbcra.com/api/documentacion
```

In [98]:
import requests
import pandas as pd
import json

In [ ]:
url = 'https://api.estadisticasbcra.com/'

In [ ]:
token = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkzNTU0NjYsInR5cGUiOiJleHRlcm5hbCIsInVzZXIiOiJwZXBlbHVpMTk4NUBnbWFpbC5jb20ifQ.gQpwTzclGcm8-6KoAB7GdcC9QeNpZV20Q_6ExzdHB_bRI-kMAK93FGOGC8INaxkovjY7Ol_cZzF1YcDp5n-JHg'
data= requests.get(url + 'prestamos', headers={'Authorization': 'Bearer {}'.format(token)}).json()

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.head()

            d      v
0  1996-04-01  47165
1  1996-04-02  47119
2  1996-04-03  47113
3  1996-04-08  47124
4  1996-04-09  47130

In [97]:
import psycopg2

In [99]:
# Establece los detalles de conexión
hostname = 'data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com'
port = '5439'
database = 'data-engineer-database'
username = 'catari_jose_coderhouse'
password = 'fdX921w2Cm'

# Establece la conexión
conn = psycopg2.connect(host=hostname, port=port, dbname=database, user=username, password=password)

In [117]:
cur = conn.cursor()

In [118]:
create_table_query = '''
    CREATE TABLE dato (
        fecha date,
        monto int,
    )
'''

In [119]:

cur.execute(create_table_query)

SyntaxError: ignored

In [49]:
conn.commit()

In [50]:
cur.close()
conn.close()